### ISSUE TITLE
Create error enums

### ISSUE THREAD

**Issue by ivajon** [s7rul/armv6-m-instruction-parser#1]
When parsing a slice of bytes like I do in [`ArmV7EM`](https://github.com/ivario123/symex/blob/generic/symex/src/arch/arm.rs) I get problems with lifetimes. As far as I can tell the issue arises when I do not unwrap the result or simply discard the error part of the result.
It seems that the borrowed data needs to have lifetime 'static for the result management to be reasonable. 

## Suggested fix

I think that it would be more beneficial to use error enums rather than static strings to represent enums, this would, aside from reducing the amount of lifetime management allow the user to match out the errors in a more predictable way. To satisfy the errors in that function I suggest an enum like this one

```rust
#[derive(Debug)]
pub enum DissasemblerError{
   InputToShort,
   Malformed32Bit,
   InvalidOpCode
}
```

**Comment by s7rul** [comment]
This is a good idea and I will solve this when I get the time. Feel free to create a pull request if you can't wait.
